/* APA 2026 website. The Google Sheet is the editable source; this is a safe offline snapshot. */
function maps(query){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;}
const TripData = {
  days: [
    {id:'2026-08-02',date:'8/2',weekday:'日',city:'桃園 → JFK → 費城',lodging:'Live! Casino & Hotel Philadelphia',summary:'抵達、取車與入住',events:[['17:30','CI 12 自桃園起飛','20:50 抵達 JFK；完成入境與取車後自駕前往費城。','已確認','travel','','','jfk|live-hotel'],['晚間','入住費城','抵達日僅安排入住、簡餐與休息。','已確認','lodging','','','live-hotel']]},
    {id:'2026-08-03',date:'8/3',weekday:'一',city:'費城',lodging:'Live! Casino & Hotel Philadelphia',summary:'UPenn、Old City 與 Phillies',events:[['上午','UPenn 心理系／University City 自助參訪','自助校園觀察，非正式拜會。','建議安排','university','','','upenn-psych|university-city'],['下午','自由鐘、獨立宮、Old City','以低負擔步行為主，預留前往球場時間。','建議安排','visit','','','liberty-bell|independence-hall|old-city'],['18:40','Nationals @ Phillies','Citizens Bank Park；建議 17:30 前抵達。','已購票','booking','https://www.mlb.com/phillies/tickets','Phillies 官方票務','citizens-bank-park']]},
    {id:'2026-08-04',date:'8/4',weekday:'二',city:'費城 → D.C.',lodging:'朋友家／寄放點',summary:'Penn 導覽後自駕前往 D.C.',events:[['10:15','Penn Campus Morning Tour','集合：Undergraduate Admissions Visitor Center，Claudia Cohen Hall Ground Floor；結束時間以確認信為準。','已報名','university','https://key.admissions.upenn.edu/portal/campus-visit','Penn Admissions','penn-admissions|claudia-cohen'],['導覽後','午餐、取車與行李緩衝','結束時間依確認信調整，不再安排博物館。','已確認','travel','','','university-city'],['午餐後','自駕前往 D.C.','入住朋友家／寄放點；不公開私人地址。','已確認','travel']]},
    {id:'2026-08-05',date:'8/5',weekday:'三',city:'Washington, D.C.',lodging:'朋友家／寄放點',summary:'APA 會前工作坊',events:[['09:00–12:00','APA CEWS #001 工作坊','Addressing Grief and Loss in Clinical Practice。','已確認','apa'],['下午','D.C. 輕量參訪或休息','依工作坊體力調整，不排高強度行程。','彈性安排','rest']]},
    {id:'2026-08-06',date:'8/6',weekday:'四',city:'Washington, D.C.',lodging:'朋友家／寄放點',summary:'APA 與第一場海報',events:[['白天','APA 精選場次','以官方議程與會場資訊為準。','待確認','apa'],['16:00–17:00','第一場海報發表','Hall D, Solutions Center, Posters｜Reverence and Fear: East Asian Evidence for Awe’s Dual Nature in VR。','已確認','poster']]},
    {id:'2026-08-07',date:'8/7',weekday:'五',city:'Washington, D.C.',lodging:'朋友家／寄放點',summary:'APA 與 D.C. 補位',events:[['白天','APA 精選場次','只選一個最有興趣的官方確認場次。','待確認','apa'],['其餘時間','D.C. 補位參訪或休息','國家廣場、博物館、白宮外觀或林肯紀念堂擇一。','彈性安排','visit','','','national-mall|smithsonian|white-house|lincoln-memorial']]},
    {id:'2026-08-08',date:'8/8',weekday:'六',city:'D.C. → Midtown',lodging:'New York Marriott Marquis',summary:'第二場海報後自駕至紐約',events:[['12:00–13:00','第二場海報發表','Hall D, Solutions Center, Posters｜Career Anxiety and Readiness in Military Cadets: A Dual-Process Model。','已確認','poster'],['下午至晚間','交流、拆海報、取行李；開車至 Midtown','飯店附近還車後入住 New York Marriott Marquis。','已確認','travel','','','marriott-marquis']]},
    {id:'2026-08-09',date:'8/9',weekday:'日',city:'紐約 Lower Manhattan',lodging:'New York Marriott Marquis',summary:'自由女神、9/11、布魯克林',events:[['09:00','Statue of Liberty Pedestal＋Ellis Island','已訂 Pedestal Reserve（3 人）；預留安檢與渡輪時間。','已訂','booking','https://www.statuecitycruises.com/','Statue City Cruises','statue-liberty|ellis-island'],['下午','Battery Park、Wall Street、9/11 Memorial & Museum','9/11 Museum 尚未訂；若渡輪延遲，改為紀念廣場。','建議預約','visit','https://www.911memorial.org/visit/museum','9/11 Memorial 官方資訊','battery-park|wall-street|charging-bull|911-museum'],['傍晚','Brooklyn Bridge、DUMBO、Juliana’s Pizza','依體力與日落時間彈性調整。','彈性安排','visit','','','brooklyn-bridge|dumbo|julianas']]},
    {id:'2026-08-10',date:'8/10',weekday:'一',city:'紐約 Chelsea／NYU',lodging:'New York Marriott Marquis',summary:'Chelsea、High Line 與 NYU',events:[['11:00','Chelsea Market 與 High Line','午餐後步行 High Line。','建議安排','visit','','','chelsea-market|high-line'],['13:30','NYU 自助參訪','Meyer Hall 心理系周邊；非正式拜會。','建議安排','university','','','nyu-meyer-hall|cafe-reggio'],['15:00–16:30','NYU Campus Tour','請於集合前約 30 分鐘抵達。','已訂','booking','https://connect.nyu.edu/portal/nyuvisit_tours','NYU 官方參訪','nyu-visitor-center'],['晚間','Greenwich Village／百老匯','百老匯音樂劇為可選。','可選','visit','','','greenwich-village|broadway']]},
    {id:'2026-08-11',date:'8/11',weekday:'二',city:'紐約 Midtown／Yankee Stadium',lodging:'New York Marriott Marquis',summary:'中城與洋基球場',events:[['10:30–13:00','Grand Central、Fifth Avenue、Rockefeller Center','中城輕量步行與午餐。','建議安排','visit','','','grand-central|fifth-avenue|rockefeller'],['14:00–17:00','Yankee Stadium Tour','以確認信所列集合入口為準，至少提早 15 分鐘。','已訂','booking','https://www.mlb.com/yankees/ballpark/tours/public','Yankees 導覽','yankee-stadium'],['17:30','提早入場領 Rumi 公仔','贈品數量與入場規則以官方最終公告為準。','已購票','booking','https://www.mlb.com/yankees/ballpark','Yankee Stadium','yankee-stadium'],['19:05','Mariners @ Yankees','散場後預留地鐵或叫車備援。','已購票','booking','https://www.mlb.com/yankees/tickets','Yankees 官方票務','yankee-stadium']]},
    {id:'2026-08-12',date:'8/12',weekday:'三',city:'紐約 AMNH／Columbia',lodging:'New York Marriott Marquis',summary:'自然歷史博物館與 Columbia',events:[['09:15','Bethesda Terrace','前往博物館前的中央公園短停。','建議安排','visit','','','bethesda-terrace'],['10:00','American Museum of Natural History','已訂；建議先看重點展區，避免超時。','已訂','booking','https://www.amnh.org/','AMNH 官方網站','amnh|levain'],['14:00','Columbia 自助校園參訪','主校園觀察；非正式拜會。','建議安排','university','','','columbia-campus'],['15:00–16:00','Columbia Campus Tour','之後可至 Schermerhorn Hall 心理系周邊與 Tom’s Restaurant。','已訂','booking','https://undergrad.admissions.columbia.edu/visit','Columbia 官方參訪','columbia-visitor|schermerhorn|toms']]},
    {id:'2026-08-13',date:'8/13',weekday:'四',city:'紐約 → JFK',lodging:'機上',summary:'返程與前往 JFK',events:[['10:30','Intrepid Museum','尚未訂；未訂到時改為飯店周邊或 Times Square。','建議預約','booking','https://intrepidmuseum.org/plan-your-visit/visitor-information/tickets','Intrepid 官方票務','intrepid'],['下午','Times Square、紀念品、打包與寄放行李','保留充足緩衝，不再安排遠距離景點。','建議安排','visit','','','times-square|marriott-marquis'],['18:30–20:30','晚餐；Uber 前往 JFK','目標 20:30 出發前往機場。','已確認','travel','','','jfk']]},
    {id:'2026-08-14',date:'8/14',weekday:'五',city:'JFK → 飛行中',lodging:'機上',summary:'返程航班',events:[['01:15','CI 11 自 JFK 起飛','以航空公司最終公告為準。','已確認','travel']]},
    {id:'2026-08-15',date:'8/15',weekday:'六',city:'桃園',lodging:'返抵臺灣',summary:'抵達桃園',events:[['05:20','抵達桃園','行程結束。','已確認','travel']]}
  ],
  bookings:[
    {id:'statue',date:'2026-08-09',time:'09:00',title:'Statue of Liberty Pedestal＋Ellis Island',status:'已訂',url:'https://www.statuecitycruises.com/',note:'預留安檢、渡輪與 Pedestal 二次安檢。'},
    {id:'911',date:'2026-08-09',time:'16:00 建議',title:'9/11 Memorial & Museum',status:'尚未訂',url:'https://www.911memorial.org/visit/museum',note:'建議 timed entry；渡輪延遲時改紀念廣場。'},
    {id:'nyu',date:'2026-08-10',time:'15:00–16:30',title:'NYU Campus Tour',status:'已訂',url:'https://connect.nyu.edu/portal/nyuvisit_tours',note:'建議 14:30 前抵達集合點。'},
    {id:'yankee-tour',date:'2026-08-11',time:'14:00–17:00',title:'Yankee Stadium Tour',status:'已訂',url:'https://www.mlb.com/yankees/ballpark/tours/public',note:'以確認信集合入口為準。'},
    {id:'yankees-game',date:'2026-08-11',time:'19:05',title:'Mariners @ Yankees',status:'已購票',url:'https://www.mlb.com/yankees/tickets',note:'公仔與入場規則以官方最後公告為準。'},
    {id:'amnh',date:'2026-08-12',time:'10:00',title:'American Museum of Natural History',status:'已訂',url:'https://www.amnh.org/',note:'先安排重點展區。'},
    {id:'columbia',date:'2026-08-12',time:'15:00–16:00',title:'Columbia Campus Tour',status:'已訂',url:'https://undergrad.admissions.columbia.edu/visit',note:'14:00 先作自助校園觀察。'},
    {id:'intrepid',date:'2026-08-13',time:'10:30 建議',title:'Intrepid Museum',status:'尚未訂',url:'https://intrepidmuseum.org/plan-your-visit/visitor-information/tickets',note:'未訂到則安排 Times Square 或飯店周邊。'},
    {id:'phillies',date:'2026-08-03',time:'18:40',title:'Nationals @ Phillies',status:'已購票',url:'https://www.mlb.com/phillies/tickets',note:'建議 17:30 前抵達球場。'}
  ],
  attractions:[
    {id:'jfk',group:'交通與住宿',name:'John F. Kennedy International Airport',detail:'8/2 抵達、取租車；8/13 晚間返回機場。',date:'8/2、8/13',url:'https://www.jfkairport.com/',mapUrl:maps('John F. Kennedy International Airport')},{id:'live-hotel',group:'交通與住宿',name:'Live! Casino & Hotel Philadelphia',detail:'8/2–8/4 已確認住宿。',date:'8/2',url:'https://www.livecasinohotel.com/philadelphia',mapUrl:maps('Live Casino Hotel Philadelphia 900 Packer Ave Philadelphia PA')},{id:'marriott-marquis',group:'交通與住宿',name:'New York Marriott Marquis',detail:'8/8 還車後入住的 Midtown 住宿。',date:'8/8',url:'https://www.marriott.com/en-us/hotels/nycmq-new-york-marriott-marquis/overview/',mapUrl:maps('New York Marriott Marquis')},
    {id:'upenn-psych',group:'費城｜8/3–8/4',name:'UPenn Psychology',detail:'8/3 心理系／University City 自助觀察；非正式拜會。',date:'8/3',url:'https://psychology.sas.upenn.edu/',mapUrl:maps('University of Pennsylvania Psychology Philadelphia')},{id:'university-city',group:'費城｜8/3–8/4',name:'University City',detail:'UPenn 校園與 8/4 導覽結束後午餐緩衝區域。',date:'8/3、8/4',url:'https://www.visitphilly.com/areas/philadelphia-neighborhoods/university-city/',mapUrl:maps('University City Philadelphia')},{id:'liberty-bell',group:'費城｜8/3–8/4',name:'Liberty Bell Center',detail:'8/3 Old City 歷史景點。',date:'8/3',url:'https://www.nps.gov/inde/planyourvisit/libertybellcenter.htm',mapUrl:maps('Liberty Bell Center Philadelphia')},{id:'independence-hall',group:'費城｜8/3–8/4',name:'Independence Hall',detail:'8/3 Old City 歷史景點。',date:'8/3',url:'https://www.nps.gov/inde/planyourvisit/independencehall.htm',mapUrl:maps('Independence Hall Philadelphia')},{id:'old-city',group:'費城｜8/3–8/4',name:'Old City Philadelphia',detail:'自由鐘與獨立宮周邊歷史街區。',date:'8/3',url:'https://www.visitphilly.com/areas/philadelphia-neighborhoods/old-city/',mapUrl:maps('Old City Philadelphia')},{id:'citizens-bank-park',group:'費城｜8/3–8/4',name:'Citizens Bank Park',detail:'8/3 18:40 Nationals @ Phillies。',date:'8/3',url:'https://www.mlb.com/phillies/ballpark',mapUrl:maps('Citizens Bank Park Philadelphia')},{id:'penn-admissions',group:'費城｜8/3–8/4',name:'Penn Admissions Visitor Center',detail:'8/4 10:15 Penn Campus Morning Tour 集合地點。',date:'8/4',url:'https://key.admissions.upenn.edu/portal/campus-visit',mapUrl:maps('Penn Admissions Visitor Center Philadelphia')},{id:'claudia-cohen',group:'費城｜8/3–8/4',name:'Claudia Cohen Hall',detail:'Admissions Visitor Center 位於 Ground Floor。',date:'8/4',url:'https://admissions.upenn.edu/',mapUrl:maps('Claudia Cohen Hall University of Pennsylvania')},
    {id:'national-mall',group:'Washington, D.C.｜彈性安排',name:'National Mall',detail:'APA 空檔的低負擔 D.C. 補位。',date:'8/5、8/7',url:'https://www.nps.gov/nama/index.htm',mapUrl:maps('National Mall Washington DC')},{id:'smithsonian',group:'Washington, D.C.｜彈性安排',name:'Smithsonian Museums',detail:'依體力選擇一間博物館。',date:'8/5、8/7',url:'https://www.si.edu/museums',mapUrl:maps('Smithsonian National Museum Washington DC')},{id:'white-house',group:'Washington, D.C.｜彈性安排',name:'White House',detail:'外觀參訪。',date:'8/7',url:'https://www.whitehouse.gov/',mapUrl:maps('White House Washington DC')},{id:'lincoln-memorial',group:'Washington, D.C.｜彈性安排',name:'Lincoln Memorial',detail:'依體力安排。',date:'8/7',url:'https://www.nps.gov/linc/index.htm',mapUrl:maps('Lincoln Memorial Washington DC')},
    {id:'statue-liberty',group:'紐約 Lower Manhattan｜8/9',name:'Statue of Liberty',detail:'09:00 已訂 Pedestal Reserve。',date:'8/9',url:'https://www.statuecitycruises.com/',mapUrl:maps('Statue of Liberty National Monument')},{id:'ellis-island',group:'紐約 Lower Manhattan｜8/9',name:'Ellis Island',detail:'自由女神渡輪行程。',date:'8/9',url:'https://www.nps.gov/elis/index.htm',mapUrl:maps('Ellis Island National Museum of Immigration')},{id:'battery-park',group:'紐約 Lower Manhattan｜8/9',name:'Battery Park',detail:'渡輪與午餐區域。',date:'8/9',url:'https://www.nycgovparks.org/parks/the-battery',mapUrl:maps('The Battery New York')},{id:'wall-street',group:'紐約 Lower Manhattan｜8/9',name:'Wall Street',detail:'Lower Manhattan 步行路線。',date:'8/9',url:'https://www.nycgo.com/boroughs-neighborhoods/manhattan/financial-district/',mapUrl:maps('Wall Street New York')},{id:'charging-bull',group:'紐約 Lower Manhattan｜8/9',name:'Charging Bull',detail:'Wall Street 周邊拍照點。',date:'8/9',url:'https://www.nyc.gov/',mapUrl:maps('Charging Bull New York')},{id:'911-museum',group:'紐約 Lower Manhattan｜8/9',name:'9/11 Memorial & Museum',detail:'Museum 尚未訂；可先參觀紀念廣場。',date:'8/9',url:'https://www.911memorial.org/',mapUrl:maps('9/11 Memorial Museum New York')},{id:'brooklyn-bridge',group:'紐約 Lower Manhattan｜8/9',name:'Brooklyn Bridge',detail:'依天候與體力安排傍晚步行。',date:'8/9',url:'https://www.nyc.gov/',mapUrl:maps('Brooklyn Bridge New York')},{id:'dumbo',group:'紐約 Lower Manhattan｜8/9',name:'DUMBO',detail:'布魯克林橋下拍照區域。',date:'8/9',url:'https://www.nycgo.com/boroughs-neighborhoods/brooklyn/dumbo/',mapUrl:maps('DUMBO Brooklyn New York')},{id:'julianas',group:'紐約 Lower Manhattan｜8/9',name:'Juliana’s Pizza',detail:'晚餐候選。',date:'8/9',url:'https://julianaspizza.com/',mapUrl:maps("Juliana's Pizza Brooklyn")},
    {id:'chelsea-market',group:'紐約 Chelsea／NYU｜8/10',name:'Chelsea Market',detail:'午餐與市場參訪。',date:'8/10',url:'https://www.chelseamarket.com/',mapUrl:maps('Chelsea Market New York')},{id:'high-line',group:'紐約 Chelsea／NYU｜8/10',name:'The High Line',detail:'Chelsea Market 後的短程步行。',date:'8/10',url:'https://www.thehighline.org/',mapUrl:maps('The High Line New York')},{id:'nyu-meyer-hall',group:'紐約 Chelsea／NYU｜8/10',name:'NYU Meyer Hall',detail:'心理系周邊自助參訪；非正式拜會。',date:'8/10',url:'https://as.nyu.edu/departments/psychology.html',mapUrl:maps('Meyer Hall NYU New York')},{id:'cafe-reggio',group:'紐約 Chelsea／NYU｜8/10',name:'Caffe Reggio',detail:'NYU 自助參訪後休息。',date:'8/10',url:'https://www.caffereggio.com/',mapUrl:maps('Caffe Reggio New York')},{id:'nyu-visitor-center',group:'紐約 Chelsea／NYU｜8/10',name:'NYU Campus Tour Meeting Point',detail:'以確認信的集合點為準。',date:'8/10',url:'https://connect.nyu.edu/portal/nyuvisit_tours',mapUrl:maps('New York University Visitor Center')},{id:'greenwich-village',group:'紐約 Chelsea／NYU｜8/10',name:'Greenwich Village',detail:'導覽後散步。',date:'8/10',url:'https://www.nycgo.com/boroughs-neighborhoods/manhattan/greenwich-village/',mapUrl:maps('Greenwich Village New York')},{id:'broadway',group:'紐約 Chelsea／NYU｜8/10',name:'Broadway Theatre District',detail:'晚間可選音樂劇。',date:'8/10',url:'https://www.broadway.org/',mapUrl:maps('Broadway Theatre District New York')},
    {id:'grand-central',group:'紐約 Midtown／Yankees｜8/11',name:'Grand Central Terminal',detail:'中城輕量步行。',date:'8/11',url:'https://www.grandcentralterminal.com/',mapUrl:maps('Grand Central Terminal New York')},{id:'fifth-avenue',group:'紐約 Midtown／Yankees｜8/11',name:'Fifth Avenue',detail:'中城步行路線。',date:'8/11',url:'https://www.nycgo.com/',mapUrl:maps('Fifth Avenue New York')},{id:'rockefeller',group:'紐約 Midtown／Yankees｜8/11',name:'Rockefeller Center',detail:'中城景點。',date:'8/11',url:'https://www.rockefellercenter.com/',mapUrl:maps('Rockefeller Center New York')},{id:'yankee-stadium',group:'紐約 Midtown／Yankees｜8/11',name:'Yankee Stadium',detail:'14:00 導覽、19:05 賽事。',date:'8/11',url:'https://www.mlb.com/yankees/ballpark',mapUrl:maps('Yankee Stadium Bronx New York')},
    {id:'bethesda-terrace',group:'紐約 AMNH／Columbia｜8/12',name:'Bethesda Terrace',detail:'前往博物館前的中央公園短停。',date:'8/12',url:'https://www.centralparknyc.org/locations/bethesda-terrace',mapUrl:maps('Bethesda Terrace Central Park New York')},{id:'amnh',group:'紐約 AMNH／Columbia｜8/12',name:'American Museum of Natural History',detail:'10:00 已訂；先看重點展區。',date:'8/12',url:'https://www.amnh.org/',mapUrl:maps('American Museum of Natural History New York')},{id:'levain',group:'紐約 AMNH／Columbia｜8/12',name:'Levain Bakery',detail:'午間簡餐候選。',date:'8/12',url:'https://levainbakery.com/',mapUrl:maps('Levain Bakery Upper West Side New York')},{id:'columbia-campus',group:'紐約 AMNH／Columbia｜8/12',name:'Columbia University',detail:'14:00 自助校園參訪。',date:'8/12',url:'https://www.columbia.edu/',mapUrl:maps('Columbia University Morningside Campus')},{id:'columbia-visitor',group:'紐約 AMNH／Columbia｜8/12',name:'Columbia Campus Tour Meeting Point',detail:'15:00 已報名導覽；以確認信集合點為準。',date:'8/12',url:'https://undergrad.admissions.columbia.edu/visit',mapUrl:maps('Columbia University Morningside Campus')},{id:'schermerhorn',group:'紐約 AMNH／Columbia｜8/12',name:'Schermerhorn Hall',detail:'心理系周邊自助參訪。',date:'8/12',url:'https://psychology.columbia.edu/',mapUrl:maps('Schermerhorn Hall Columbia University')},{id:'toms',group:'紐約 AMNH／Columbia｜8/12',name:'Tom’s Restaurant',detail:'校園附近咖啡／餐食。',date:'8/12',url:'https://tomsrestaurant.net/',mapUrl:maps("Tom's Restaurant Morningside Heights New York")},
    {id:'intrepid',group:'紐約返程日｜8/13',name:'Intrepid Museum',detail:'10:30 建議；目前尚未訂。',date:'8/13',url:'https://intrepidmuseum.org/',mapUrl:maps('Intrepid Sea Air Space Museum New York')},{id:'times-square',group:'紐約返程日｜8/13',name:'Times Square',detail:'紀念品與返程前市區安排。',date:'8/13',url:'https://www.timessquarenyc.org/',mapUrl:maps('Times Square New York')}
  ],
  logistics:{lodging:[['8/2–8/4','Live! Casino & Hotel Philadelphia','900 Packer Ave., Philadelphia；已確認住宿。'],['8/4–8/8','朋友家／寄放點','不公開私人地址。'],['8/8–8/13','New York Marriott Marquis','Midtown Manhattan；8/8 飯店附近還車後入住。']],transport:[['8/2','JFK 取租車 → 費城','入境、取車後直接前往飯店；抵達日不排其他行程。'],['8/4','費城 → D.C.','午餐後自駕，入住朋友家／寄放點。'],['8/8','D.C. → Midtown','第二場海報後取行李，自駕至 Midtown；飯店附近還車。'],['8/13–8/14','Midtown → JFK → 桃園','20:30 Uber 出發；CI 11 01:15 起飛。']]},
  apa:{commitments:[['8/5 09:00–12:00','CEWS #001 工作坊','Addressing Grief and Loss in Clinical Practice: Differential Diagnosis and Intervention Strategies。'],['8/6 16:00–17:00','第一場海報','Hall D, Solutions Center, Posters｜Reverence and Fear: East Asian Evidence for Awe’s Dual Nature in VR。'],['8/8 12:00–13:00','第二場海報','Hall D, Solutions Center, Posters｜Career Anxiety and Readiness in Military Cadets: A Dual-Process Model。']],focus:['優先主題：軍事心理學、職涯焦慮、軍校生與青年發展、心理測驗與心理計量、情緒調節、悲傷與失落、VR、AI 與心理健康。','沒有 APA 官方確認的場次、地點與時間，一律標示為待確認；海報前後保留報到、準備、交流、拍照與收拾緩衝。','會後整理聚焦可帶回國防大學的課程、心理測驗教材、研究設計、國際交流與後續合作。']},
  checklist:[['flight','確認 CI 12／CI 11 航班、護照效期與線上報到時間','出發前 72 小時再次確認。'],['car','確認 JFK 取車、保險、駕照及 8/8 Midtown 還車門市','不在公開網站填入訂位編號。'],['poster','完成兩場海報檔案、攜帶方式、會場與發表前後緩衝','8/6、8/8 為不可衝突時段。'],['tickets','下載自由女神、NYU、洋基導覽／球賽、AMNH、Columbia 電子票','將電子票保存在手機與離線備份。'],['pending','完成 9/11 Museum 與 Intrepid 是否預約的決定','若不訂，預先啟用備案。'],['packing','完成行李、轉接頭、常用藥、雨具與球場／博物館安檢準備','8/13 預留打包與行李寄放時間。']],
  risks:['抵達、跨城市移動、海報發表及返程日不加塞景點。','自由女神、球場、博物館均可能安檢；提早到達且保留 App 叫車／地鐵備援。','球賽賽程、贈品、入場規則、博物館與景點開放時間，以官方最終公告為準。','若天候、交通或體力不佳，優先保留已訂活動，其他景點直接取消或縮短。']
};

function source(){
  const r=window.TripContent||{};
  if(!r.days?.length)return TripData;
  const baseDays=new Map(TripData.days.map(day=>[day.id,day]));
  const days=r.days.map(day=>{const base=baseDays.get(day.id);if(!base)return day;const baseEvents=new Map(base.events.map(event=>[event[1],event]));return {...base,...day,events:day.events.map(event=>{const old=baseEvents.get(event[1]);return old&& !event[7]?[...event,old[7]||'']:event;})};});
  const remotePlaces=(r.attractions||[]).filter(place=>place.id);
  const mergedPlaces=new Map(TripData.attractions.map(place=>[place.id,place]));remotePlaces.forEach(place=>mergedPlaces.set(place.id,{...mergedPlaces.get(place.id),...place}));
  return {...TripData,...r,days,attractions:[...mergedPlaces.values()],logistics:{...TripData.logistics,...(r.logistics||{})},apa:{...TripData.apa,...(r.apa||{})}};
}
function esc(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function statusClass(s=''){return /已訂|已購票|已確認/.test(s)?'confirmed':/尚未|待|建議預約/.test(s)?'pending':'';}
function status(s){return `<span class="status ${statusClass(s)}">${esc(s)}</span>`;}
function link(url,label='官方資訊'){return url?`<a class="official-link" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)} ↗</a>`:'';}
function mapLink(url,label='Google Maps 導航'){return url?`<a class="map-link" href="${esc(url)}" target="_blank" rel="noopener">📍 ${esc(label)} ↗</a>`:'';}
function placeLinks(ids,d){if(!ids)return '';const lookup=new Map((d.attractions||[]).map(p=>[p.id,p]));return ids.split('|').map(id=>lookup.get(id)).filter(Boolean).map(p=>mapLink(p.mapUrl,p.name)).join('');}
function nav(){const b=document.querySelector('.nav-toggle'),n=document.querySelector('.nav-links');if(b&&n)b.addEventListener('click',()=>{const open=n.classList.toggle('open');b.setAttribute('aria-expanded',open);});}
function renderHome(d){const g=document.querySelector('#homeGlance');if(!g)return;g.innerHTML=[['城市路線','JFK → 費城 → D.C. → 紐約 → JFK'],['學術節點','APA 工作坊＋兩場海報'],['已訂重點','自由女神、NYU、洋基、AMNH、Columbia']].map(x=>`<article class="glance-card"><strong>${x[0]}</strong><small>${x[1]}</small></article>`).join(''); const next=d.bookings.filter(x=>/已訂|已購票/.test(x.status)).sort((a,b)=>a.date.localeCompare(b.date))[0];const box=document.querySelector('#nextBooking');if(next)box.innerHTML=`<div class="date-mark"><strong>${next.date.slice(5).replace('-','/')}</strong><small>${esc(next.time)}</small></div><div><p class="eyebrow">${status(next.status)}</p><strong>${esc(next.title)}</strong><div>${esc(next.note)}</div>${link(next.url)}</div>`;const tl=document.querySelector('#homeTimeline');tl.innerHTML=d.days.map(day=>`<a class="timeline-row" href="itinerary.html#${day.id}"><span class="timeline-date">${day.date}（${day.weekday}）</span><span><strong>${esc(day.city)}</strong><small>${esc(day.summary)}</small></span>${day.events.some(e=>/已訂|已購票|已確認/.test(e[3]))?status('已排定'):''}</a>`).join('');}
function renderItinerary(d){const tabs=document.querySelector('#dayTabs'),out=document.querySelector('#daySchedule');if(!tabs||!out)return;let selected=location.hash.slice(1)||d.days[0].id;function draw(){const day=d.days.find(x=>x.id===selected)||d.days[0];tabs.innerHTML=d.days.map(x=>`<button class="day-tab ${x.id===day.id?'active':''}" data-day="${x.id}">${x.date} ${x.weekday}</button>`).join('');out.innerHTML=`<div class="day-head" id="${day.id}"><h2>${esc(day.date)}（${esc(day.weekday)}）｜${esc(day.city)}</h2><p>${esc(day.summary)} · 住宿：${esc(day.lodging)}</p></div>`+day.events.map(e=>`<article class="schedule-card"><div class="schedule-time">${esc(e[0])}</div><div><h3>${esc(e[1])}</h3><p>${esc(e[2])}</p><div class="schedule-meta">${status(e[3])}${link(e[5],e[6]||'官方資訊')}${placeLinks(e[7],d)}</div></div></article>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.day;history.replaceState(null,'','#'+selected);draw();});}draw();}
function renderApa(d){const el=document.querySelector('#apaCommitments');if(el)el.innerHTML=d.apa.commitments.map(x=>`<article class="feature-item"><div class="meta">${esc(x[0])}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('');const focus=document.querySelector('#apaFocus');if(focus)focus.innerHTML=d.apa.focus.map(x=>`<p>${esc(x)}</p>`).join('');}
function renderAttractions(d){const el=document.querySelector('#attractionGroups');if(!el)return;const groups={};d.attractions.forEach(x=>(groups[x.group]??=[]).push(x));el.innerHTML=Object.entries(groups).map(([name,items])=>`<section class="place-group"><h2>${esc(name)}</h2><div class="place-grid">${items.map(x=>`<article class="place-card"><h3>${esc(x.name)}</h3><p>${esc(x.detail)}</p><small>${esc(x.date)}</small><div class="place-actions">${link(x.url)}${mapLink(x.mapUrl)}</div></article>`).join('')}</div></section>`).join('');}
function renderLogistics(d){const l=document.querySelector('#lodgingList');if(l)l.innerHTML=d.logistics.lodging.map(x=>`<article class="info-card"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></article>`).join('');const t=document.querySelector('#transportList');if(t)t.innerHTML=d.logistics.transport.map(x=>`<article class="feature-item"><div class="meta">${esc(x[0])}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('');}
function renderPrep(d){const list=document.querySelector('#checklist'),progress=document.querySelector('#checkProgress');if(list){const saved=JSON.parse(localStorage.getItem('apa2026-checklist')||'{}');function draw(){const done=d.checklist.filter(x=>saved[x[0]]).length;progress.textContent=`${done} / ${d.checklist.length} 已完成`;list.innerHTML=d.checklist.map(x=>`<label class="check-item ${saved[x[0]]?'done':''}"><input type="checkbox" data-check="${x[0]}" ${saved[x[0]]?'checked':''}><span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></span></label>`).join('');list.querySelectorAll('input').forEach(i=>i.onchange=()=>{saved[i.dataset.check]=i.checked;localStorage.setItem('apa2026-checklist',JSON.stringify(saved));draw();});}draw();}const p=document.querySelector('#pendingBookings');if(p)p.innerHTML=d.bookings.filter(x=>/尚未/.test(x.status)).map(x=>`<article class="feature-item"><div class="meta">${esc(x.date)} · ${esc(x.time)}</div><h3>${esc(x.title)}</h3><p>${esc(x.note)}</p>${link(x.url)}</article>`).join('')||'<div class="empty">目前沒有待處理預約。</div>';const r=document.querySelector('#riskList');if(r)r.innerHTML=d.risks.map(x=>`<p>${esc(x)}</p>`).join('');}
function init(){const d=source();nav();renderHome(d);renderItinerary(d);renderApa(d);renderAttractions(d);renderLogistics(d);renderPrep(d);if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
(window.TripContentReady||Promise.resolve()).finally(init);
